name: pnplab_mlcourse
channels:
    # ...default conda channels already set up
    - conda-forge # for nilearn, rise, jupyterthemes, jupyter_contrib_nbextensions and pip (pip is used for mglearn)
dependencies:
    - python=3.7
    - jupyter=1.0.0
    - rise=5.5.1
    - numpy=1.17.2
    - pandas=0.25.1
    - nilearn=0.5.2
    - matplotlib=3.1.1
    - jupyterthemes=0.20.0
    - scikit-learn=0.21.3
    - seaborn=0.9.0
    
    # for Split Cells and Markdown (enable in-markdown output variable) Notebook extensions
    # through-conda nbextensions install also installs js and css file
    # automatically.
    - jupyter_contrib_nbextensions
    
    - pip=19.2.3 # for mglearn
    - pip:
       - mglearn


