#!/bin/sh
#
# This file is automatically run by mybinder.org at server startup.

# Install jupyterlab-git extension (already added through conda with environment.yml).
# -- actually not - this is a cherry-picked commit.
# jupyter lab build

# Install Split Cells Notebook extension through jupyter-nbextension extension
# (which is an extension for unofficial extensions).
jupyter nbextension enable splitcell/splitcell

# Install Python Markdown Notebook extension.
jupyter nbextension enable python-markdown/python-markdown

# Trust all notebooks by default so they run python-markdown extension at launch time.
# Unsecure locally, but since it happens inside a docker container, we do not worry
# too much.
for file in */*.ipynb; do jupyter trust "$file"; done
